######################## default configuration ####################
baseURL = "http://www.baerlanfriedblog.com/"
languageCode = "en-us"
title = "Baer Blog"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
[[menu.main]]
name = "About"
URL = "about/"
weight = 1

[[menu.main]]
name = "Posts"
URL = "blog/"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact/"
weight = 3

# footer menu
[[menu.footer]]
name = "About"
URL = "about/"
weight = 1

[[menu.footer]]
name = "Posts"
URL = "blog/"
weight = 2

[[menu.footer]]
name = "Contact"
URL = "contact/"
weight = 3

[[menu.footer]]
name = "Privacy Policy"
URL = "privacypolicy/"
weight = 4

[[menu.footer]]
name = "Terms & Conditions"
URL = "termsandconditions/"
weight = 4


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Baer Lanfried"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "+33 06 52 45 44 72"
email = "blanfried@gmail.com"
location = "Brooklyn, New York"
# copyright
copyright = "| copyright &copy; 2021 [Themefisher](https://themefisher.com/hugo-themes/) All Rights Reserved | Adapted by Lanfried Web Services |"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Join My Newsletter"
content = "If you would like to follow along and receive updates on my new videos and blogs, subscribe to the newsletter! *Check your spam if you do not receive the confirmation email.*"

# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "youtube"
icon = "ti-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UC9l_27z0J81ZiwOoc_-uQGg"

[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/baer.lanfried/"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/blanfried"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/baer-lanfried-488ab61aa/"

[[params.social]]
title = "youtube"
icon = "ti-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UC9l_27z0J81ZiwOoc_-uQGg"
