######################## default configuration ####################
baseURL = "http://www.baerlanfriedblog.com/"
languageCode = "en-us"
title = "Baer Blog"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"
[[params.plugins.css]]
URL = "plugins/font-awesome/css/all.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
[[menu.main]]
name = "About"
URL = "about/"
weight = 1

[[menu.main]]
name = "Posts"
URL = "blog/"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact/"
weight = 3

# footer menu
[[menu.footer]]
name = "About"
URL = "about/"
weight = 1

[[menu.footer]]
name = "Posts"
URL = "blog/"
weight = 2

[[menu.footer]]
name = "Contact"
URL = "contact/"
weight = 3

[[menu.footer]]
name = "Privacy Policy"
URL = "privacypolicy/"
weight = 4

[[menu.footer]]
name = "Terms & Conditions"
URL = "termsandconditions/"
weight = 4


#################### default parameters ################################
[params]
logo = "images/logo.svg"
home = "Home"
# Meta data
description = "This is meta description"
author = "Baer Lanfried"
# Google Analytics
googleAnalitycsID = "Your ID"
# Contact Information
mobile = ""
email = "blanfried@gmail.com"
location = "San Diego, CA"
# copyright
copyright = "Copyright &copy; 2024 Baer Lanfried"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Join My Newsletter"
content = "If you would like to follow along and receive updates on my new videos and blogs, subscribe to the newsletter! *Check your spam if you do not receive the confirmation email.*"

# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "Linkedin"
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/baer-lanfried-488ab61aa/"

[[params.social]]
title = "Github"
icon = "fab fa-github"
link = "http://github.com/blanfried"

[[params.social]]
title = "Youtube"
icon = "fab fa-youtube"
link = "https://www.youtube.com/@BaerLanfried"

[[params.social]]
title = "Facebook"
icon = "fab fa-facebook"
link = "https://www.facebook.com/baer.lanfried"

[[params.social]]
title = "Instagram"
icon = "fab fa-instagram"
link = "https://www.instagram.com/baerlanfried/"

[[params.social]]
title = "Medium"
icon = "fab fa-medium"
link = "https://medium.com/@baerlanfried_99543"

[[params.social]]
title = "Substack"
icon = "fa-solid fa-bookmark"
link = "https://baerlanfried.substack.com/"